version: '1.0'
name: gitee-lams-path-vsce-publish
displayName: gitee-lams-path-vsce-publish
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
variables:
  VSCE_TOKEN: guj5kyls7fxn3lvp5v6c7aahcy5yufjx2qldhmgo2znimtakltxa
stages:
  - name: publish
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - 'npm install '
          - '# 发布'
          - ./node_modules/.bin/vsce publish -p ${VSCE_TOKEN}
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
